#!/bin/bash
userhome=$1
username=$2
password=$3

if [ "X$password" == "X" ];then
    password="abc123"
fi

useradd -s /bin/bash -d $userhome -m $username &&\
( echo $password; echo $password ) | passwd --stdin $username
